### ISSUE TITLE
Null return value from advice does not match primitive return type

### ISSUE THREAD

**Issue by MrNocTV** [microservices-practical/microservices-v9#2]
The cause of this problem is from the `getStatsForUser` functionality. If a user enters an incorrect attempt and also that user hasn't had any correct attempts before, then we will get this error at `int getTotalScoreForUser(@Param("userId") final Long userId);` in `ScoreCardRepository`.

My solution is:

1. Change the return type from `int` to `Integer` -> `Integer getTotalScoreForUser(@Param("userId") final Long userId);` 
2. Add this `if` condition in method `public GameStats retrieveStatsForUser(final Long userId)` of `GameServiceImpl`. The new implementation of the method looks like this:

```
    @Override
    public GameStats retrieveStatsForUser(final Long userId) {
        Integer score = scoreCardRepository.getTotalScoreForUser(userId);
        if (score == null) {
            return new GameStats(userId, 0, Collections.emptyList());
        }
        List<BadgeCard> badgeCards = badgeCardRepository
                .findByUserIdOrderByBadgeTimestampDesc(userId);
        return new GameStats(userId, score, badgeCards.stream()
                .map(BadgeCard::getBadge).collect(Collectors.toList()));
    }
```
Please check and allow me to create a new PR if this is a correct solution.

**Comment by mechero** [comment]
Hi @MrNocTV, you found indeed a problem in the book's edition. Please check this repository, it's actually fixed the way you're suggesting 😄

https://github.com/microservices-practical/microservices-v9/blob/master/gamification/src/main/java/microservices/book/gamification/repository/ScoreCardRepository.java#L22

Nice finding anyway 🕵, I'm glad you're following the approach of typing the code yourself, it's way better to learn.

Kind regards
